/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AcceptInviteRouteImport } from "./routes/accept-invite";
import { Route as CalendarRouteImport } from "./routes/calendar";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SavedRouteImport } from "./routes/saved";
import { Route as ProfileRouteImport } from "./routes/profile";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/dashboard";
import { Route as ClosingSoonRouteImport } from "./routes/closing-soon";
import { Route as AppliedRouteImport } from "./routes/applied";
import { Route as AdminRouteImport } from "./routes/admin";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AdminIndexRouteImport } from "./routes/admin.index";
import { Route as TenderIdRouteImport } from "./routes/tender.$id";
import { Route as AdminLoginRouteImport } from "./routes/admin.login";

const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: "/accept-invite",
  path: "/accept-invite",
  getParentRoute: () => rootRouteImport,
} as any);
const CalendarRoute = CalendarRouteImport.update({
  id: "/calendar",
  path: "/calendar",
  getParentRoute: () => rootRouteImport,
} as any);
const SavedRoute = SavedRouteImport.update({
  id: "/saved",
  path: "/saved",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileRoute = ProfileRouteImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const ClosingSoonRoute = ClosingSoonRouteImport.update({
  id: "/closing-soon",
  path: "/closing-soon",
  getParentRoute: () => rootRouteImport,
} as any);
const AppliedRoute = AppliedRouteImport.update({
  id: "/applied",
  path: "/applied",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: "/admin",
  path: "/admin",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AdminRoute,
} as any);
const TenderIdRoute = TenderIdRouteImport.update({
  id: "/tender/$id",
  path: "/tender/$id",
  getParentRoute: () => rootRouteImport,
} as any);
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => AdminRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/accept-invite": typeof AcceptInviteRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/applied": typeof AppliedRoute;
  "/calendar": typeof CalendarRoute;
  "/closing-soon": typeof ClosingSoonRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/saved": typeof SavedRoute;
  "/signup": typeof SignupRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/tender/$id": typeof TenderIdRoute;
  "/admin/": typeof AdminIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/accept-invite": typeof AcceptInviteRoute;
  "/applied": typeof AppliedRoute;
  "/calendar": typeof CalendarRoute;
  "/closing-soon": typeof ClosingSoonRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/saved": typeof SavedRoute;
  "/signup": typeof SignupRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/tender/$id": typeof TenderIdRoute;
  "/admin": typeof AdminIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/accept-invite": typeof AcceptInviteRoute;
  "/admin": typeof AdminRouteWithChildren;
  "/applied": typeof AppliedRoute;
  "/calendar": typeof CalendarRoute;
  "/closing-soon": typeof ClosingSoonRoute;
  "/dashboard": typeof DashboardRoute;
  "/login": typeof LoginRoute;
  "/profile": typeof ProfileRoute;
  "/saved": typeof SavedRoute;
  "/signup": typeof SignupRoute;
  "/admin/login": typeof AdminLoginRoute;
  "/tender/$id": typeof TenderIdRoute;
  "/admin/": typeof AdminIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/accept-invite"
    | "/admin"
    | "/applied"
    | "/calendar"
    | "/closing-soon"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/saved"
    | "/signup"
    | "/admin/login"
    | "/tender/$id"
    | "/admin/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/accept-invite"
    | "/applied"
    | "/calendar"
    | "/closing-soon"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/saved"
    | "/signup"
    | "/admin/login"
    | "/tender/$id"
    | "/admin";
  id:
    | "__root__"
    | "/"
    | "/accept-invite"
    | "/admin"
    | "/applied"
    | "/calendar"
    | "/closing-soon"
    | "/dashboard"
    | "/login"
    | "/profile"
    | "/saved"
    | "/signup"
    | "/admin/login"
    | "/tender/$id"
    | "/admin/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AcceptInviteRoute: typeof AcceptInviteRoute;
  AdminRoute: typeof AdminRouteWithChildren;
  AppliedRoute: typeof AppliedRoute;
  CalendarRoute: typeof CalendarRoute;
  ClosingSoonRoute: typeof ClosingSoonRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  ProfileRoute: typeof ProfileRoute;
  SavedRoute: typeof SavedRoute;
  SignupRoute: typeof SignupRoute;
  TenderIdRoute: typeof TenderIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/accept-invite": {
      id: "/accept-invite";
      path: "/accept-invite";
      fullPath: "/accept-invite";
      preLoaderRoute: typeof AcceptInviteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/saved": {
      id: "/saved";
      path: "/saved";
      fullPath: "/saved";
      preLoaderRoute: typeof SavedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile": {
      id: "/profile";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard": {
      id: "/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/closing-soon": {
      id: "/closing-soon";
      path: "/closing-soon";
      fullPath: "/closing-soon";
      preLoaderRoute: typeof ClosingSoonRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/applied": {
      id: "/applied";
      path: "/applied";
      fullPath: "/applied";
      preLoaderRoute: typeof AppliedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/calendar": {
      id: "/calendar";
      path: "/calendar";
      fullPath: "/calendar";
      preLoaderRoute: typeof CalendarRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin": {
      id: "/admin";
      path: "/admin";
      fullPath: "/admin";
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/": {
      id: "/admin/";
      path: "/";
      fullPath: "/admin/";
      preLoaderRoute: typeof AdminIndexRouteImport;
      parentRoute: typeof AdminRoute;
    };
    "/tender/$id": {
      id: "/tender/$id";
      path: "/tender/$id";
      fullPath: "/tender/$id";
      preLoaderRoute: typeof TenderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/admin/login": {
      id: "/admin/login";
      path: "/login";
      fullPath: "/admin/login";
      preLoaderRoute: typeof AdminLoginRouteImport;
      parentRoute: typeof AdminRoute;
    };
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute;
  AdminIndexRoute: typeof AdminIndexRoute;
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
};

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRouteWithChildren,
  AppliedRoute: AppliedRoute,
  CalendarRoute: CalendarRoute,
  ClosingSoonRoute: ClosingSoonRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  TenderIdRoute: TenderIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
